In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [6]:
a+b
#a[2:6]


array([6, 6, 6, 6, 6])

In [15]:
b

array([5, 4, 3, 2, 1])

In [16]:
np.add(a, b)

array([6, 6, 6, 6, 6])

In [17]:
np.subtract(a, b)

array([-4, -2,  0,  2,  4])

In [14]:
np.dot(a, b)

35

In [7]:
a.append(b)

AttributeError: 'numpy.ndarray' object has no attribute 'append'