In [77]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# Set up fake X and Y
X = np.random.randn(100,3)
Y = np.random.binomial(1, 0.5, 100) #  with one trials 

logreg = LogisticRegression() #classifier
logreg.fit(X, Y)#fit data

# coefficients:
logreg.coef_ 

X_new = np.random.randn(2, 3)

# predict class:
y_pred = logreg.predict(X_new)


# predicted probability:
y_pp = logreg.predict_proba(X_new)

In [78]:
#  X[0:1]
# print(Y[0:5],X[0:5])
# print(logreg.coef_ )
y_pred

# y_pp


array([1, 1])

In [80]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33)

logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)

In [86]:
 from sklearn.metrics import confusion_matrix
confusion = np.array(confusion_matrix(Y_test, Y_pred))
 print(confusion)
[[168  31]
[ 46  85]]

  # calculate true positives, the number of 1s correctly predicted to be 1
TP = confusion[0,0]

  # calculate false positives, the number of 0s incorrectly predicted to be 1
FP  = confusion[1,0]

  # calculate true negatives, the number of 0s correctly predicted to be 0
TN = confusion[1,1]

  # calculate false negatives, the number of 1s incorrectly predicted to be 0
FN = confusion[0,1]

SyntaxError: invalid syntax (<ipython-input-86-3e6921ac8e84>, line 4)

In [96]:
from sklearn.metrics import confusion_matrix

confusion = np.array(confusion_matrix(Y_test, Y_pred))
print(confusion)
# [[168 31]
#  [46 85]]



  # calculate true positives, the number of 1s correctly predicted to be 1
TP = confusion[0,0]

  # calculate false positives, the number of 0s incorrectly predicted to be 1
FP  = confusion[1,0]

  # calculate true negatives, the number of 0s correctly predicted to be 0
TN = confusion[1,1]

  # calculate false negatives, the number of 1s incorrectly predicted to be 0
FN = confusion[0,1]

[[ 7  9]
 [ 7 10]]
