In [37]:
import sklearn.preprocessing
from sklearn.preprocessing import MaxAbsScaler
from sklearn.pipeline import Pipeline
import numpy as np


In [45]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

max_abs_scaler = MaxAbsScaler() # model
X_train_maxabs = max_abs_scaler.fit_transform(X_train) # fit data than transform
X_train_maxabs                
X_test = np.array([[ -3., -1.,  4.]]) # new array
X_test_maxabs = max_abs_scaler.transform(X_test) # scale the data
                




In [46]:
X_train_maxabs 

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

In [47]:
max_abs_scaler.scale_

array([ 2.,  1.,  2.])

In [41]:
X_test_maxabs

array([[-1.5, -1. ,  2. ]])

In [67]:

from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])  

enc.n_values_

enc.feature_indices_




array([0, 2, 5, 9])

In [59]:
enc = OneHotEncoder()
enc

OneHotEncoder(categorical_features='all', dtype=<type 'float'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [68]:
enc.n_values_


array([2, 3, 4])

In [61]:
enc.feature_indices_

AttributeError: 'OneHotEncoder' object has no attribute 'feature_indices_'

In [66]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])  

enc.n_values_

enc.feature_indices_

enc.transform([[0, 1, 1]]).toarray()


array([[ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.]])

In [63]:
enc.n_values_

array([2, 3, 4])

In [64]:
enc.feature_indices_



array([0, 2, 5, 9])

In [71]:
#encode categorical integer features using a one-of-k scheme like labelbinarizer
from sklearn.preprocessing import OneHotEncoder

data = [[1], [3], [5]]

encoder = OneHotEncoder()
encoder.fit(data)

print(encoder.transform([
           [0],
           [1],
           [2],
           [3],
           [4],
           [5],
           
       ]).toarray())


# By using sklearn.preprocessing.LabelBinarizer. OneHotEncoder takes an integer and creates dummy variables from it.

# [8:29]  
# from sklearn import preprocessing
# # # lb = preprocessing.LabelBinarizer()
# # lb.fit([1, 2, 6, 4, 2])
# # # LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)
# # # lb.classes_
# # #array([1, 2, 4, 6])
# # # lb.transform([1, 6])

[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]]
